<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>system_manager</AssemblyName>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.0-rc.1.25451.107" />
    <PackageReference Include="System.Management" Version="9.0.8" />
    <PackageReference Include="Vortice.DXGI" Version="3.6.2" />
    <PackageReference Include="Vortice.Mathematics" Version="1.9.3" />
    <PackageReference Include="InputSimulator" Version="1.0.4">
      <NoWarn>NU1701</NoWarn>
    </PackageReference>
  </ItemGroup>

</Project>
